query posts {
  posts {
    posts {
      _id
      content
      createdAt
      creator {
          _id
          firstName
          lastName
          photoSm
      }
      updatedAt
      likes {
        _id
      }
      replies {
        _id
      }
      media
    }
  }
}