subscription updatePost {
    updatePost {
     _id
     content
     createdAt
     updatedAt
     creator {
         _id
         firstName
         lastName
         photoSm
     }   
    }
}